name: lms-microservices

services:
  api-gateway:
    container_name: lms-api-gateway
    build:
      context: ./apps/api-gateway
      dockerfile: Dockerfile
    env_file:
      - ./apps/api-gateway/.env
    environment:
      NODE_ENV: production
      API_GATEWAY_PORT: 3000
      AUTH_SERVICE_URL: http://auth:3001
      USER_SERVICE_URL: http://user:3002
      COURSE_SERVICE_URL: http://course:3004
      API_DOCS_URL: http://api-docs:80
    ports:
      - "3000:3000"
    expose:
      - "3000"
    restart: unless-stopped
    init: true
    read_only: true
    networks:
      - backend

  auth:
    container_name: lms-auth-service
    build:
      context: ./apps/auth-service-mongo
      dockerfile: Dockerfile
    env_file:
      - ./apps/auth-service-mongo/.env
    environment:
      NODE_ENV: production
      AUTH_SERVICE_PORT: 3001
    ports:
      - "3001:3001"
    expose:
      - "3001"
    restart: unless-stopped
    init: true
    read_only: true
    networks:
      - backend

  user:
    container_name: lms-user-service
    build:
      context: ./apps/user-service
      dockerfile: Dockerfile
    env_file:
      - ./apps/user-service/.env
    environment:
      NODE_ENV: production
      USER_SERVICE_PORT: 3002
    ports:
      - "3002:3002"
    expose:
      - "3002"
    restart: unless-stopped
    init: true
    read_only: true
    networks:
      - backend

  course:
    container_name: lms-course-service
    build:
      context: ./apps/course-service
      dockerfile: Dockerfile
    env_file:
      - ./apps/course-service/.env
    environment:
      NODE_ENV: production
      COURSE_SERVICE_PORT: 3004
    ports:
      - "3004:3004"
    expose:
      - "3004"
    restart: unless-stopped
    init: true
    read_only: true
    networks:
      - backend

  email:
    container_name: lms-email-service
    build:
      context: ./apps/email-service
      dockerfile: Dockerfile
    env_file:
      - ./apps/email-service/.env
    environment:
      NODE_ENV: production
      EMAIL_SERVICE_PORT: 3003
    ports:
      - "3003:3003"
    expose:
      - "3003"
    restart: unless-stopped
    init: true
    read_only: true
    networks:
      - backend

networks:
  backend:
    driver: bridge
